- hosts: vsd_inplace_upgrade_nodes[0]
  gather_facts: no
  any_errors_fatal: true
  run_once: true
  pre_tasks:
    - name: Lets run VSD DB Backup hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vsd_dbbackup
          - upgrade_vsds
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsd-dbbackup

- hosts: vsd_inplace_upgrade_nodes
  gather_facts: no
  serial: 1
  pre_tasks:
    - name: Lets run VSD inplace upgrade hooks
      include_role:
        name: hooks
        tasks_from: main
      vars:
        - hooks_file_path: "{{ hook }}"
        - hook_location:
          - vsd_inplace_upgrade_nodes
      loop: "{{ hooks | default([]) }}"
      loop_control:
        loop_var: hook
  roles:
    - vsd-upgrade-inplace
